version: '3.4'
  
services:
  backend-app:
    image: docker.io/library/weatherapi:0.1
    container_name: backend-app
    ports:
      - "5086:80"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sep6.database.windows.net;Initial Catalog=bestmoviesdb;Persist Security Info=False;User ID=sachin;Password=Password1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
      - ASPNETCORE_URLS=http://+:80

    
  