version: '3.4'

networks:
  dev:
    driver: bridge
    
services:
  backend-app:
    image: docker.io/library/weatherapi:0.1
    depends_on: 
      - "app-db"
    container_name: backend-app
    ports:
      - "8088:80"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app-db;Port=5432;Database=SampleDb; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
        
        
  app-db:
    image: postgres:latest
    container_name: app-db
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDb
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
  
volumes:
    app_data:
    
  