// This should give error:
#GET http://localhost:5086/Test/authorized

 ###
POST http://localhost:5086/Auth/Login
Content-Type: application/json

 {
    "username": "admin",
    "password": "admin"
 }

###

GET http://localhost:5086/Test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5Zjc5ZDM4MS1mMmM2LTRlYTQtYTJjZS0zNGMzNDFjMTNkMTYiLCJpYXQiOiIxMS8yOC8yMDIzIDM6NDM6MjcgUE0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU2FjaGluIiwiRW1haWwiOiJzYWNoaW5AYmFyYWwuY29tIiwiZXhwIjoxNzAxMTkzNDA3LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6ImJlc3Rtb3ZpZXMtZnJvbnRlbmQifQ.6-4uv09RrbLc_BnVGeDQ-XMaXKn6TsiVVWW-0y2iKY_Uf2L2qSUx2f8ziVSbI26YoPFBJV8g8LZ7WBzNc2K7dA

###

GET http://localhost:5086/Test/try
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5Zjc5ZDM4MS1mMmM2LTRlYTQtYTJjZS0zNGMzNDFjMTNkMTYiLCJpYXQiOiIxMS8yOC8yMDIzIDM6NDM6MjcgUE0iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU2FjaGluIiwiRW1haWwiOiJzYWNoaW5AYmFyYWwuY29tIiwiZXhwIjoxNzAxMTkzNDA3LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6ImJlc3Rtb3ZpZXMtZnJvbnRlbmQifQ.6-4uv09RrbLc_BnVGeDQ-XMaXKn6TsiVVWW-0y2iKY_Uf2L2qSUx2f8ziVSbI26YoPFBJV8g8LZ7WBzNc2K7dA
